# Generated by Django 4.1.13 on 2023-11-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_date_appointment_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
